name: Run Notebook and Upload CSV to Google Drive

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Sesuaikan versi Python yang diinginkan

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter
          pip install -r requirements.txt # Ganti dengan perintah instalasi dependencies yang sesuai

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute notebook.ipynb --ExecutePreprocessor.timeout=-1

      - name: Upload to gdrive
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: ./Airbnb Listings Bangkok_cleaned.csv
          folderId: ${{ secrets.FOLDER_ID }}
          credentials: ${{ secrets.GDRIVE_SA_KEY }}
