name: Run Notebook and Upload CSV to Google Drive

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Sesuaikan versi Python yang diinginkan
      - name: Update Pull Request
        uses: actions/github-script@v3.1.0
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `${ "${{ steps.terraform_fmt.outcome }}" == "success" ? "\u2714" : "\u274c" } Terraform Format and Style 🖌
            ${ "${{ steps.terraform_init.outcome }}" == "success" ? "\u2714" : "\u274c" } Terraform Initialization ⚙️
            ${ "${{ steps.terraform_plan.outcome }}" == "success" ? "\u2714" : "\u274c" } Terraform Plan 📖
            ${ "${{ steps.terraform_validate.outcome }}" == "success" ? "\u2714" : "\u274c" } Terraform Validation 🤖

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter
          pip install -r requirements.txt # Ganti dengan perintah instalasi dependencies yang sesuai

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute notebook.ipynb --ExecutePreprocessor.timeout=-1

      - name: Save CSV file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: generated-csv-files
          path: ./Airbnb_Listings_Bangkok_cleaned.csv # Ganti dengan path file CSV yang dihasilkan oleh notebook

      - name: Download site content
        uses: actions/download-artifact@v2
        with:
          name: generated-csv-files
      - name: Archive site content
        uses: thedoctor0/zip-release@master # buat kompres
        with:
          filename: downloaded-artifact.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }} # This token is provided by Actions, you do not need to create your own token
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./downloaded-artifact.zip
          asset_name: cleaned_data.zip
          asset_content_type: application/zip

      - name: Upload to gdrive
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: ./downloaded-artifact.zip
          folderId: ${{ secrets.FOLDER_ID }}
          credentials: ${{ secrets.GDRIVE_SA_KEY }}
