name: Run Notebook and Upload CSV to Google Drive

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Sesuaikan versi Python yang diinginkan

      - name: Get registration token
        id: getRegToken
        run: |
          curl -X POST -H \"Accept: application/vnd.github.v3+json\"  -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/myprofile/myrepo/actions/runners/registration-token

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter
          pip install -r requirements.txt # Ganti dengan perintah instalasi dependencies yang sesuai

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute notebook.ipynb --ExecutePreprocessor.timeout=-1

      - name: Save CSV file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: generated-csv-files
          path: ./Airbnb_Listings_Bangkok_cleaned.csv # Ganti dengan path file CSV yang dihasilkan oleh notebook

      - name: Download site content
        uses: actions/download-artifact@v2
        with:
          name: generated-csv-files
      - name: Archive site content
        uses: thedoctor0/zip-release@master # buat kompres
        with:
          filename: downloaded-artifact.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Hasil data cleaning
          draft: false
          prerelease: false

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }} # This token is provided by Actions, you do not need to create your own token
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./downloaded-artifact.zip
          asset_name: cleaned_data.zip
          asset_content_type: application/zip

      - name: Upload to gdrive
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: ./downloaded-artifact.zip
          folderId: ${{ secrets.FOLDER_ID }}
          credentials: ${{ secrets.GDRIVE_SA_KEY }}
